"""
TileGenie - Genie-Powered Production Intelligence App
Databricks Community Contest: Genie-Powered App Challenge

Showcasing "Genie at the Core":
- All insights powered by Genie's natural language understanding
- Display Genie's SQL generation process
- Show Genie's suggested follow-up questions
- Quick action buttons for common executive questions (all Genie-powered)
- Rich responses with text, SQL, and suggestions
"""

import streamlit as st
import os
import time

st.set_page_config(
    page_title="TileGenie - Genie-Powered Intelligence",
    page_icon="🟦",
    layout="wide"
)

st.markdown("""
<style>
    .main-header {
        background: linear-gradient(135deg, #1e3a8a 0%, #3b82f6 100%);
        padding: 2rem;
        border-radius: 10px;
        margin-bottom: 2rem;
    }
    .main-header h1 { color: white; margin-bottom: 0.5rem; }
    .main-header p { color: #bfdbfe; font-size: 1.1rem; margin: 0; }
</style>
""", unsafe_allow_html=True)

# Initialize WorkspaceClient
@st.cache_resource
def get_workspace_client():
    from databricks.sdk import WorkspaceClient
    return WorkspaceClient()

GENIE_SPACE_ID = os.getenv("GENIE_SPACE_ID", "").replace("genie://", "")

if not GENIE_SPACE_ID:
    st.error("❌ GENIE_SPACE_ID not configured")
    st.stop()

# Session state initialization
if "conversation_id" not in st.session_state:
    st.session_state.conversation_id = None
if "messages" not in st.session_state:
    st.session_state.messages = []

# Header
st.markdown('<div class="main-header"><h1>🟦 TileGenie</h1><p>🧞‍♂️ Powered by Databricks Genie - Your AI Production Intelligence Partner</p></div>', unsafe_allow_html=True)

# Quick Action Buttons (All Genie-Powered)
st.markdown("### ⚡ Executive Quick Insights")
st.caption("🎯 Click any button - Genie analyzes your data in real-time")

col1, col2, col3, col4 = st.columns(4)

with col1:
    if st.button("📊 Yesterday's Production", use_container_width=True, type="primary"):
        st.session_state['quick_question'] = "Why was production reduced yesterday?"
        st.rerun()

with col2:
    if st.button("📦 Inventory Status", use_container_width=True, type="primary"):
        st.session_state['quick_question'] = "How much stock do we have in each warehouse?"
        st.rerun()

with col3:
    if st.button("🔮 Next Quarter Forecast", use_container_width=True, type="primary"):
        st.session_state['quick_question'] = "What is the expected production of Porcelain-Glossy-24x24 for next quarter?"
        st.rerun()

with col4:
    if st.button("⚙️ Machine Health", use_container_width=True, type="primary"):
        st.session_state['quick_question'] = "Which machines had the most downtime this week?"
        st.rerun()

st.markdown("---")

# Display conversation history
for idx, msg in enumerate(st.session_state.messages):
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        
        # Show suggested questions from Genie
        if msg["role"] == "assistant" and "suggestions" in msg and msg["suggestions"]:
            st.markdown("")
            st.markdown("💡 **Genie suggests you ask:**")
            for i, suggestion in enumerate(msg["suggestions"]):
                if st.button(f"➡️ {suggestion}", key=f"suggest_{idx}_{i}", use_container_width=True):
                    st.session_state['quick_question'] = suggestion
                    st.rerun()
        
        # Show SQL query generated by Genie
        if msg["role"] == "assistant" and "sql" in msg:
            with st.expander("🔍 See the SQL Query Genie Generated", expanded=False):
                st.caption("Genie wrote this query to answer your question:")
                st.code(msg["sql"], language="sql")

# Chat input
if 'quick_question' in st.session_state:
    user_input = st.session_state['quick_question']
    del st.session_state['quick_question']
else:
    user_input = st.chat_input("✨ Ask Genie anything about your tile production...")

if user_input:
    w = get_workspace_client()
    
    st.session_state.messages.append({"role": "user", "content": user_input})
    with st.chat_message("user"):
        st.markdown(user_input)
    
    with st.chat_message("assistant"):
        with st.spinner("🧞‍♂️ Genie is analyzing your data..."):
            try:
                if not st.session_state.conversation_id:
                    response = w.genie.start_conversation(space_id=GENIE_SPACE_ID, content=user_input)
                    st.session_state.conversation_id = response.conversation_id
                    message_id = response.message_id
                else:
                    response = w.genie.create_message(
                        space_id=GENIE_SPACE_ID,
                        conversation_id=st.session_state.conversation_id,
                        content=user_input
                    )
                    message_id = response.message_id
                
                for _ in range(60):
                    message = w.genie.get_message(space_id=GENIE_SPACE_ID, conversation_id=st.session_state.conversation_id, message_id=message_id)
                    
                    status = str(message.status) if hasattr(message, 'status') else None
                    
                    if status and 'COMPLETED' in status:
                        # Extract rich content from Genie response
                        content = "No response"
                        sql_query = None
                        suggested_questions = []
                        
                        if message.attachments:
                            for attachment in message.attachments:
                                # Extract text answer
                                if hasattr(attachment, 'text') and attachment.text:
                                    if hasattr(attachment.text, 'content'):
                                        content = attachment.text.content
                                
                                # Extract SQL query
                                if hasattr(attachment, 'query') and attachment.query:
                                    if hasattr(attachment.query, 'query'):
                                        sql_query = attachment.query.query
                                
                                # Extract suggestions
                                if hasattr(attachment, 'suggested_questions') and attachment.suggested_questions:
                                    if hasattr(attachment.suggested_questions, 'questions'):
                                        suggested_questions = list(attachment.suggested_questions.questions)[:3]
                        
                        # Display answer
                        st.markdown(content)
                        
                        # Store message with metadata
                        msg_data = {"role": "assistant", "content": content}
                        if sql_query:
                            msg_data["sql"] = sql_query
                        if suggested_questions:
                            msg_data["suggestions"] = suggested_questions
                        
                        st.session_state.messages.append(msg_data)
                        
                        # Display suggestions
                        if suggested_questions:
                            st.markdown("")
                            st.markdown("💡 **Genie suggests you ask:**")
                            for i, suggestion in enumerate(suggested_questions):
                                if st.button(f"➡️ {suggestion}", key=f"suggest_new_{i}", use_container_width=True):
                                    st.session_state['quick_question'] = suggestion
                                    st.rerun()
                        
                        # Display SQL
                        if sql_query:
                            with st.expander("🔍 See the SQL Query Genie Generated", expanded=False):
                                st.caption("Genie wrote this query to answer your question:")
                                st.code(sql_query, language="sql")
                        
                        break
                    elif status and 'FAILED' in status:
                        st.error(f"Genie encountered an issue: {message.error if hasattr(message, 'error') else status}")
                        break
                    
                    time.sleep(2)
            except Exception as e:
                st.error(f"Error: {str(e)}")

# Sidebar
with st.sidebar:
    st.markdown("### 🏆 Contest Entry")
    st.write("**Databricks Community Contest**")
    st.caption("Genie-Powered App Challenge")
    
    st.markdown("---")
    
    st.markdown("### 🧞‍♂️ About Genie")
    st.info(
        "**Genie at the Core**\n\n"
        "✅ Natural language to SQL\n"
        "✅ Intelligent query generation\n"
        "✅ Contextual suggestions\n"
        "✅ Real-time data analysis\n\n"
        "All insights powered by Genie analyzing 16 gold tables!"
    )
    
    st.markdown("---")
    
    if st.button("🔄 Reset Conversation", use_container_width=True):
        st.session_state.conversation_id = None
        st.session_state.messages = []
        st.rerun()
